Add Submariner CRDs
datreeio/CRDs-catalog pull request #212
Opened 2023-09-11 09:09 UTC by ronaldm-hollywoodbets

Add CRDs for Submariner
https://github.com/submariner-io/submariner

2023-09-11 09:12 UTC, ronaldchBET approved these changes

2023-09-13 20:11 UTC, eyarz commented
@ronaldm-hollywoodbets can you please also add a reference link to the github repo that contains the CRD itself?

2023-09-13 20:22 UTC, ronaldm-hollywoodbets commented
> @ronaldm-hollywoodbets can you please also add a reference link to the github repo that contains the CRD itself?

Hi @eyarz, I've updated the description with the link to the Submariner CRDs

2023-10-26 11:10 UTC, eyarz requested changes
the folder name should be [group]/[kind_apiVersion]
you need to replace `multicluster.x-k8s.io` with `submariner.io`

2024-03-24 22:06 UTC, closed without merging