Import networking.gke.io CRDs and improve crd-extractor script
datreeio/CRDs-catalog pull request #422
Opened 2024-11-20 12:25 UTC by kishorviswanathan

2024-11-20 12:28 UTC, kishorviswanathan commented
@eyarz As we discussed in #266 

Also the crd-extraction script was painfully slow. I had 280 CRDs in the cluster. So tweaked it to fetch CRDs in parallel as well.

2024-11-24 08:28 UTC, eyarz requested changes
@kishorviswanathan please open a separate PR for updating the crd-extractor because if I will need rollback the crd or the extractor I don't want them to be coupled.

2024-12-18 13:30 UTC, kishorviswanathan commented
@eyarz Made the changes and created a new PR #441.

2024-12-23 08:32 UTC, eyarz approved these changes

2024-12-23 08:33 UTC, merged